### ISSUE TITLE
Error: Failed to install 'unknown package' from GitHub:  

### ISSUE THREAD

**Issue by Mukhtabdi** [obaezvil/SpatIndex#1]
> remotes::install_github("obaezvil/SpatInex")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`obaezvil`) and repo name (`SpatInex`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by wisemuck** [comment]
I have solved the issue by correcting the spelling of the package name to "SpatIdnex".

**Comment by obaezvil** [comment]
It should be `SpatIndex` instead of `SpatInex` :)
