### ISSUE TITLE
Downloading GitHub repo obaezvil/SpatIndex@HEAD Skipping 1 packages not available: spatstat.core ── R CMD build ─Error: Failed to install 'SpatIndex' from GitHub:   ! System command 'Rcmd.exe' failed

### ISSUE THREAD

**Issue by Mukhtabdi** [obaezvil/SpatIndex#2]

**Comment by Mukhtabdi** [comment]
It seems that the installation of the 'SpatIndex' package from GitHub failed due to the missing dependency of 'spatstat.core'.

The package `spatstat.core`’ is not currently available for this version of R.

It's mentioned [here](https://github.com/spatstat/spatstat.core) in the GitHub that the `spatstat.core` will be replaced by two packages `spatstat.explore ` and `spatstat.model`

I extremely need to use 'SpatIndex' package. Could you solve this issue please?

**Comment by obaezvil** [comment]
Hi wisemuck, indeed the package `spatstat.core`  is no longer available in CRAN.
I will have to mdify some things before updating the package but you can install it from github meanwhile as follows:

`remotes::install_github("https://github.com/spatstat/spatstat.core")`

Then, SpatIndex should work perfectly fine!

**Comment by Mukhtabdi** [comment]
His obaezvil,
It worked. thanks
