### ISSUE TITLE
The package could be loaded

### ISSUE THREAD

**Issue by Mtrsh** [obaezvil/SpatIndex#3]
Hey @obaezvil,

when I try to load your package I get this: 

remotes::install_github("obaezvil/SpatInex")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`obaezvil`) and repo name (`SpatInex`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

Do you know what could be wrong ? 

thank you.

**Comment by obaezvil** [comment]
Hi @Mtrsh, you have a typo in the repo name. It should be SpatIndex not SpatInex. The "d" is missing :)
